language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - docker
  - redis

install:
  - pip install coverage codecov

# command to run tests
script:
  - coverage run test_strmatch.py
  - codecov